### ISSUE TITLE
Pushing a View doesn't work (iOS 15 Preview)

### ISSUE THREAD

**Issue by vexonius** [rundfunk47/stinsen#11]
Hello, I'm using Stinsen lib for navigating through app flows. Modal presenting works as expected, but pushing a view doesn't work. I'm using xcode 13.4 & tried 13.5 beta, but still viewcontroller doesn't get pushed. Following the examples from this repo. 

Is it possible that ios 15 is not supported?

**Comment by rundfunk47** [comment]
Hi! It should work on iOS 15, the only problem is that the current version (1.0.11) doesn't build due to this bug: https://developer.apple.com/forums/thread/682351 . So you might need to use 1.0.10 until it is fixed.

Have you tried running StinsenApp? Does that work (try using the testbed)? Which version of Stinsen are you using?

**Comment by vexonius** [comment]
I was using version 1.0.9. Pushing finally worked after replacing NavigationCoordinatable with ViewCoordinatable... Is there some requirement for pushing NavigationCoordinatable? I followed the app example from the repo.

**Comment by rundfunk47** [comment]
As per the documentation:
```
* NavigationCoordinatable - For navigational flows. Make sure to wrap these in a NavigationViewCoordinator somewhere if you wish to push on the navigation stack.
* ViewCoordinatable - Just a view and routes that do not push but rather replace the entire view, can be used for instance when switching between logged in/logged out.
```
so it sounds like a `NavigationCoordinatable` is what you want to use here. You also need a `NavigationViewCoordinatable` (the name has changed to `NavigationViewCoordinator` in recent versions so it depends on the version you are using) that wraps around the `NavigationCoordinatable` you are using, similar to how you need a `NavigationView` in order to get `NavigationLink` to work in SwiftUI.
