### ISSUE TITLE
Stinsen + IQKeyboardManager Navigation Bar issue

### ISSUE THREAD

**Issue by savage7** [rundfunk47/stinsen#19]
Hi 😊 

I have a chat like screen within a `NavigationCoordinatable` with a `TextField` on the bottom. When I press the TextField the screen should move up. We use `IQKeyboardManager` for general TextField handling.

With Stinsen the NavigationBar is moved outside the Screen:
![Simulator Screen Shot - iPhone 12 - 2021-09-02 at 07 32 13](https://user-images.githubusercontent.com/971353/131788328-de97c825-524c-4965-b945-204f3ac297df.png)

If should look like this:
![Simulator Screen Shot - iPhone 12 - 2021-09-02 at 07 32 00](https://user-images.githubusercontent.com/971353/131788325-668d92eb-aced-42f8-a0d3-fbf5c5de0fdd.png)

I think I already found the root cause: 
`NavigationViewCoordinatorView` sets `StackNavigationViewStyle`. When I remove this,
 it looks as expected.

It tried to set the style directly to `DefaultNavigationViewStyle` inside the View but thats overruled by the NavigationViewCoordinatorView style.

Is there a proper workaround for this? (I've found none)
Why is StackNavigationViewStyle used explicitly? Can we make that somehow configurable or is StackNavigationViewStyle needed?

I modified the example app to show the problem. I've modified the LoginScreen and added IQKeyboardManager.
[Stinsen + IQKeyboardManager Issue.zip](https://github.com/rundfunk47/stinsen/files/7096464/Stinsen.%2B.IQKeyboardManager.Issue.zip)

Thanks ALOT for your help and ongoing work in this great project 🥇  😄

**Comment by rundfunk47** [comment]
Hi! Thanks for the kind words :) Older versions of Stinsen did not use StackNavigation, but what I found was that it made the code really confusing because it needed to account for what I assume are bugs in SwiftUI, which Stack does not have. The bugs are not fixed in latest beta iOS either. Even when having those workarounds it didn't really work well either. It was a long time ago but I think it had to do with isActive only worked correcly on the first and last view (master and detail), which makes dismissing coordinators not to work all of the time if you for instance have screens A B C D E F and try to dismiss the coordinator which started on screen C (since SwiftUI thinks that screen is already "dismissed").
