### ISSUE TITLE
How can I inject a mock Router object to ViewModel for testing purpose?

### ISSUE THREAD

**Issue by YuantongL** [rundfunk47/stinsen#32]
I like now we can route in ViewModel, it would be great if we can also test our ViewModel, then we need to be able to inject a mock.

**Comment by rundfunk47** [comment]
There's no way of doing that in a good way unfortunately right now. You can inject a router with ```RouterStore.shared.store```, but however, that requires a concrete class - and since all coordinators are final, it makes this pretty awkward: you'd need some kind of variable ```var isMock: Bool``` for every coordinator and reimplement most functions. So it's either the way you posted above, or you can use your another dependency injection framework and do the injecting in onAppear. 

I suppose one way of enabling this within Stinsen would be, when defining a coordinator, you would be able to define the type to use when storing the coordinator? sort of like

```protocol TodoCoordinatorProtocol {
      func routeTo(_: TodoRoute)
}

final class TodoCoordinator: NavigationCoordinatable {
    var routerStoreType = TodoCoordinatorProtocol.self // <-- This

   [...]
}```

and then to recall it:

```
final class StandardTodoViewModel: TodoViewModel {
  @RouterObject var router: NavigationRouter<TodoCoordinatorProtocol>

  func onTapTodo(id: UUID) {
    router.routeTo(.todo(id))
  }
```

Would this be a good solution you think? I'm not 100% sure it would be feasible though!

**Comment by YuantongL** [comment]
@rundfunk47 Thanks for the update, that makes sense to me. Feel free to close this issue.
